/* periodic boundary */
pbc(x):= (x/Ly - floor(x/Ly))*Ly;

/* box size */
Lx: 10.0;
Ly: 10.0;

/* rate */
R: 1.0;

/* velocity of the atom in Y direction */
vel: 10.0;

/* position of the atom */
x0: 5.0;
y0: 9.0;

/* time interval */
ti: 1.0;

/* the new Y is the same as in periodic */
y: pbc(y0+vel*ti);

/* the new VX was updated */
ncross: 1;
vx: -ncross*R*Ly;

/* position in x */
tcross: (Ly-y0)/vel;
x: pbc(x0 + tcross*0 + (ti - tcross)*vx);