ndim: 3;
w(r):= A * (1 + 3*r/h)*(1 - r/h)^3;

I: if ndim=2 then integrate(integrate( w(r)*r, r, 0, h), phi, 0, 2*%pi)
else integrate(integrate(integrate( w(r)*r^2*sin(omega), r, 0, h), phi, 0, 2*%pi), omega, 0, %pi);

A: rhs(solve(I=1, 'A)[1]);

load("draw")$
block([h: 1],
  draw2d( explicit( w(r), r, 0, h),
    color='red,
    explicit( dw(r), r, 0, h)));

dw(r):= ''(factor(diff(w(r), r)));

factor(w(r)), numer;
grind(factor(dw(r))), numer;
