/* solve equation of motion for two DPD atoms */
H: 10.0;
r0: 1.0;
m: 1.0;
uvec(ri, rj):=(rj - ri)/abs(rj - ri);

/* fene potential */
U(r):= -0.5*H*r0*log(1-(r/r0)^2);
/* fene force */
F(r):= ''(diff(U(r), r));
  
eq1: vi;
eq2: vj;
eq3: uvec(xi, xj) * F( abs(xi-xj) );
eq4: uvec(xj, xi) * F( abs(xj-xi) );
vars: [xi, xj, vi, vj];

sol: rk([eq1, eq2, eq3, eq4], vars, [0.0, 0.5, 0, 0], [t, 0, 1.0, 1.0e-2])$
last(sol)[3] - last(sol)[2];
