/* solve equation of motion for one atom */
eq: 'diff(x, t, 2) = 'diff(x, t);

/* time step in LAMMPS */
dt: 0.01;

/* initial condition from lammps */
x0: 5.0;
v0: 1.0;

/* number of steps */
nstep: 80;
/* wall position */
pxwall: 6.0;

eqofm: ic2(ode2(eq, x, t ), t=0, x=x0, 'diff(x, t)=v0)$
xend: float(rhs(subst( [t=nstep*dt], eqofm)));

/* take reflection into account */
pxwall + (6.0 - xend);
