# LAMMPS does not compute temperature for single atom
echo     both

atom_modify map array sort 0.0 0.0
region		box block 0 10 0 10 0 10 units box
create_box	1 box
mass            1 1

#create_atoms 1 box
create_atoms 1 single 5 5 5 units box
group        fst id == 1
velocity     fst set 1.0 0.0 0.0 units box

# Uncomment this line to get correct temperature
#create_atoms 1 single 4 5 5 units box

timestep     0.0
fix	     1 all nve
run 0
