/*
Jayne, B. C. Swimming in Constricting (Elaphe g. guttata) and
Nonconstricting (Nerodia fasciata pictiventris) Colubrid
Snakes. Copeia 1985, 195 (1985).

*/


eq: [AMP = m[1]*X + b[1],
     lambda  = m[2]*X + b[2],
     AMP  = m[3]*lambda + b[3]];

lambda_ref: expand(subst([eq[2]], rhs(eq[3])));
subst( [m[2]=0.274, b[2]=46.7, m[3]=0.289, b[3]=-9.51], lambda_ref);

subst( [m[2]=0.456, b[2]=40.5, m[3]=0.189, b[3]=-4.15], lambda_ref);




