function dump() {
    # print the number of atoms
    print n
    # print a commend line
    print " file generated by punto2xyz"
    # print all atoms
    for (i=1; i<n+1; i++) {
	split(store[i], aux)
	printf "%s          %9.7f        %9.7f       %9.7f\n",
	    "H", aux[1], aux[2], aux[3]+0.0
    }
    n=0
}

NF {
    n++
    store[n]=$0
}

!NF {
    dump()
}

END {
    dump()
}
